version: '2'

services:
  php:
    image: php:7.2-fpm-alpine
    ports:
      - "9000:80"
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
